#!/bin/bash

export PATH=/var/vcap/packages/ruby/bin:$PATH

RUN_DIR=/var/vcap/sys/run/terracotta_gateway_ng
LOG_DIR=/var/vcap/sys/log/terracotta_gateway_ng
JOB_DIR=/var/vcap/jobs/terracotta_gateway_ng

PIDFILE=$RUN_DIR/terracotta_gateway.pid

source /var/vcap/packages/common/utils.sh

case $1 in

  start)
    pid_guard $PIDFILE "Terracotta gateway"

    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR

    echo $$ > $PIDFILE

    <% if properties.syslog_aggregator %>
    /var/vcap/packages/syslog_aggregator/setup_syslog_forwarder.sh $JOB_DIR/config
    <% end %>

    exec /var/vcap/packages/terracotta_gateway_ng/terracotta/bin/terracotta_gateway \
         -c $JOB_DIR/config/terracotta_gateway.yml \
         >>$LOG_DIR/terracotta_gateway.stdout.log \
         2>>$LOG_DIR/terracotta_gateway.stderr.log

    ;;

  stop)
    kill_and_wait $PIDFILE

    ;;

  *)
    echo "Usage: $0 {start|stop}"

    ;;

esac
