#!/bin/bash
export PATH=/var/vcap/packages/ruby/bin:$PATH

TERRACOTTA_ADMIN_USER=<%= properties.terracotta_node.admin_user || "terracotta_admin" %>
TERRACOTTA_ADMIN_GROUP=<%= properties.terracotta_node.admin_group || "admin" %>
TERRACOTTA_ADMIN_PASSWD_HASH=<%= properties.terracotta_node.admin_passwd_hash || "" %>

COMMON_DIR=/var/vcap/store/terracotta_common
RUN_DIR=/var/vcap/sys/run/terracotta_node
LOG_DIR=/var/vcap/sys/log/terracotta_node
JOB_DIR=/var/vcap/jobs/terracotta_node_ng
PIDFILE=$RUN_DIR/terracotta_node.pid

<%
migration = properties.service_migration
lifecycle = properties.service_lifecycle
%>

MIG_DIR=<%= migration && migration.mount_point || "/var/vcap/services_migration" %>
<% if lifecycle and lifecycle.nfs_server %>
SNAPSHOT_DIR=<%= lifecycle.mount_point || "/var/vcap/services_snapshot" %>
MT_OPTS="-t nfs"
MT_EXPORT=<%= lifecycle.nfs_server.address %>:<%= lifecycle.nfs_server.export_dir %>
<% end %>

source /var/vcap/packages/common/utils.sh

case $1 in

  start)
    pid_guard $PIDFILE "Terracotta node"

    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR

    echo $$ > $PIDFILE

    if [ -n "$TERRACOTTA_ADMIN_PASSWD_HASH" ]; then
      # do a mod in addition to the add in order to support password changes
      USER_ARGS="-g $TERRACOTTA_ADMIN_GROUP -p $TERRACOTTA_ADMIN_PASSWD_HASH $TERRACOTTA_ADMIN_USER"
      /usr/sbin/useradd -m -s /bin/bash $USER_ARGS
      /usr/sbin/usermod $USER_ARGS
    fi

    <% if properties.syslog_aggregator %>
    /var/vcap/packages/syslog_aggregator/setup_syslog_forwarder.sh $JOB_DIR/config
    <% end %>

    mkdir -p $MIG_DIR

    <% if lifecycle && lifecycle.nfs_server %>
    mkdir -p $SNAPSHOT_DIR
    check_mount "$MT_OPTS" "$MT_EXPORT" "$SNAPSHOT_DIR"
    <% end %>

    chmod +x $JOB_DIR/config/terracotta_backup
    $JOB_DIR/config/terracotta_backup start

    (crontab -l | sed /terracotta_logrotate/d; cat $JOB_DIR/config/terracotta_logrotate.cron) | sed /^$/d | crontab

    mkdir -p $COMMON_DIR/bin
    mkdir -p $COMMON_DIR/config
    rsync -arl $JOB_DIR/bin/warden_service_ctl $COMMON_DIR/bin
    rsync -arl $JOB_DIR/bin/pre_service_start.sh $COMMON_DIR/bin
    rsync -arl $JOB_DIR/bin/terracotta_ctl $COMMON_DIR/bin
    rsync -arl /var/vcap/packages/common/utils.sh $COMMON_DIR/bin
    chmod -R 755 $COMMON_DIR/bin

    exec /var/vcap/packages/terracotta_node_ng/terracotta/bin/terracotta_node \
         -c $JOB_DIR/config/terracotta_node.yml \
         >>$LOG_DIR/terracotta_node.stdout.log \
         2>>$LOG_DIR/terracotta_node.stderr.log

    ;;

  stop)
    kill_and_wait $PIDFILE 60

    chmod +x $JOB_DIR/config/terracotta_backup
    $JOB_DIR/config/terracotta_backup stop
    <% if lifecycle && lifecycle.nfs_server %>
    umount $SNAPSHOT_DIR
    <% end %>

    ;;

  *)
    echo "Usage: $0 {start|stop}"

    ;;

esac
